title:             Martin Song Blog Test 180302
email:             bimstarzero@gmail.com
description:       테스트
author:            Martin_Song
baseurl:           "/bimstar2.github.io"
url:               "https://bimstar2.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
